//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratego.Net.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public int RedPlayerId { get; set; }
        public int BluePlayerId { get; set; }
        public byte[] GameState { get; set; }
    
        public virtual Player BluePlayer { get; set; }
        public virtual Player RedPlayer { get; set; }
    }
}
