//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratego.Net.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public int InviteId { get; set; }
        public int SenderId { get; set; }
        public int RecipientId { get; set; }
    
        public virtual Player Recipient { get; set; }
        public virtual Player Sender { get; set; }
    }
}
