//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratego.Net.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.BlueGames = new HashSet<Game>();
            this.RedGames = new HashSet<Game>();
            this.ReceivedInvites = new HashSet<Invite>();
            this.SentInvites = new HashSet<Invite>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Game> BlueGames { get; set; }
        public virtual ICollection<Game> RedGames { get; set; }
        public virtual ICollection<Invite> ReceivedInvites { get; set; }
        public virtual ICollection<Invite> SentInvites { get; set; }
    }
}
